### ISSUE TITLE
[Request] FAQ answer about the sidebar ordering not working

### ISSUE THREAD

**Issue by tcurdt** [malnvenshorn/OctoPrint-FilamentManager#128]
#### What were you doing?

I am trying have the filament manager below the state on the left.
(see FAQ)

#### What did you expect to happen?

I modified the `config.yaml` according to the FAQ

```
...
appearance:
  components:
    order:
      sidebar:
      - connection
      - state
      - plugin_filementmanager
      tab:
      - temperature
...
```
and then I restarted the service.
(Shouldn't there als be the file section in the sidebar config?)

#### What happened instead?

Unfortunately the order has not changed.

#### Link to octoprint.log

[octoprint.log](https://github.com/malnvenshorn/OctoPrint-FilamentManager/files/2458642/octoprint.log)

#### Further information

I have read the FAQ and provided all required information.
