### ISSUE TITLE
Plugin name for config.yaml - reorder in sidebar

### ISSUE THREAD

**Issue by pandel** [malnvenshorn/OctoPrint-FilamentManager#29]
Hi Sven!

First, many thanks for your great plugin. Absolutely useful addition to OctoPrint!

One question: with the last update you changed the fixed position of the plugin to a configurable one. I tried to reorder the plugins in the sidebar, but somehow it did not work. I am not sure what I did wrong....

Could you be so nice to tell me the correct plugin name to use in the appearance section? Or do you have an example on how to set this up for the old plugin position? Sorry for the question, but I am not used to modify config.yaml directly...

Many thanks,
Holger

**Comment by malnvenshorn** [comment]
Of course. To restore the old position under the printer state you need the following in your config.yaml

```
appearance:
  components:
    order:
      sidebar:
      - connection
      - state
      - plugin_filamentmanager
```
